### ISSUE TITLE
codeblock does not render correctly

### ISSUE THREAD

**Issue by andreacremese** [twoyao/beautiful-hexo#3]
Trying to use `beautiful-hexo` for hexo as I really like it - well done with the design.

I wan into a snag though: `{% codeblock %}` tag in my posts do not render correctly.

For example the following code block in a post

```
{% codeblock lang:javascript %}
function someClass() {
    this.name = "Andrea";
    setTimeout(function () {
        console.log(`Hello ${this.name}`);
    },1000)
}
var p = new someClass(); // will output only 'Hello'
{% endcodeblock %}
```

with beautiful-hexo renders as

![image](https://cloud.githubusercontent.com/assets/4465618/17355458/9a8d6a9a-5905-11e6-8f21-813892206c45.png)

while with other themes renders normally, with highligh.js
![image](https://cloud.githubusercontent.com/assets/4465618/17355502/dec20ca2-5905-11e6-843e-27df90eea3d5.png)

It seems like highligh is running as the code has the correct classes, but the css does not seem to be included in the rendered. 

Any suggestion on how to fix this?

**Comment by twoyao** [comment]
After some research, I choose to use [highlight.js](https://github.com/isagalaev/highlight.js), not hexo default highlight. 

Update theme to last version 34281bf. 
Disable hexo highlight in site _config.yml :

``` yml
highlight:
  enable: false
```

Make sure theme highlight in theme _config.yml is enabled(default to enabled ) :

``` yml
highlight:
  enable: true
# or use any highlight.js style
#  style_path: "//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/styles/default.min.css"
  style_path: "/css/highlight.css"
```

In your posts, just write markdown code. i.e.

``````
```javascript
function someClass() {
    this.name = "Andrea";
    setTimeout(function () {
        console.log(`Hello ${this.name}`);
    },1000)
}
```
``````

see [effect](http://twoyao.cn/beautiful-hexo/2016/01/02/test-markdown/)
